GET http://localhost:3000/users/get?id=1

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/save
Content-Type: application/json

{
  "id": 3,
  "name": "Victor",
  "age": 26
}

###
